---
# tasks file for redis_role

- name: Download Redis
  get_url:
    url: https://download.redis.io/releases/redis-6.0.4.tar.gz
    dest: /tmp/redis.tar.gz
    mode: 0644

- name: Extract redis.tar.gz into /usr/bin/redis-server
  unarchive:
    src: redis.tar.gz
    dest: /usr/bin/redis-server

- name: Build Redis
  make:
    chdir: /usr/bin/redis-server

- name: Configure Redis.
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"
    mode: 0644

- name: Configure Sentinel.
  template:
    src: sentinel.conf.j2
    dest: "/etc/redis/sentinel.conf"
    mode: 0644

- name: Register Service.
  service: "name=redis-server state=started enabled=yes"
  notify: Restart Redis

...
