---
# tasks file for redis_role

- name: Install Redis.
  apt:
    name: "redis-server"
    state: present

- name: Configure Redis.
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"
    mode: 0644

- name: Configure Sentinel.
  template:
    src: sentinel.conf.j2
    dest: "/etc/redis/sentinel.conf"
    mode: 0644
  notify: Restart Redis Service

- name: Register Service to Run Redis on Boot.
  service: "name=redis-server state=started enabled=yes"

...
