---
# tasks file for redis_role

- name: Install Make
  become: yes
  become_user: root
  package:
    name: "build-essential"
    state: present

- name: Download and extract redis-6.0.4.tar.gz into /usr/bin/.
  become: yes
  become_user: root
  unarchive:
    src: http://download.redis.io/releases/redis-6.0.4.tar.gz
    dest: /usr/bin/
    remote_src: yes

- name: Rename Directory
  become: yes
  become_user: root
  command: mv /usr/bin/redis-6.0.4 /usr/bin/redis-server

- name: Build Redis
  become: yes
  become_user: root
  make:
    chdir: /usr/bin/redis-server

- name: Install Redis
  become: yes
  become_user: root
  make:
    chdir: /usr/bin/redis-server
    target: install

- name: Create Redis Configuration Directory.
  become: yes
  become_user: root
  file:
    path: /etc/redis/
    state: directory
    mode: 0755

#- name: Execute Redis Install Script.
#  become: yes
#  become_user: root
#  command: bash /usr/bin/redis-server/utils/install_server.sh

- name: Configure Redis.
  become: yes
  become_user: root
  template:
    src: redis.conf.j2
    dest: "/etc/redis/redis.conf"
    mode: 0644

- name: Configure Sentinel.
  become: yes
  become_user: root
  template:
    src: sentinel.conf.j2
    dest: "/etc/redis/sentinel.conf"
    mode: 0644

- name: Copy Redis Server Service File.
  become: yes
  become_user: root
  copy:
    src: /usr/bin/redis-server/utils/systemd-redis_server.service
    dest: /etc/systemd/system/redis-server.service
    remote_src: yes

- name: Replace in Redis Server Service File
  become: yes
  become_user: root
  replace:
    path: /etc/systemd/system/redis-server.service
    regexp: '--supervised systemd --daemonize no'
    replace: '/etc/redis/redis.conf'

- name: Replace in Redis Server Service File
  become: yes
  become_user: root
  replace:
    path: /etc/systemd/system/redis-server.service
    regexp: 'Type=notify'
    replace: 'Type=forking'

- name: Copy Redis Sentinel Service File.
  become: yes
  become_user: root
  copy:
    src: /usr/bin/redis-server/utils/systemd-redis_server.service
    dest: /etc/systemd/system/redis-sentinel.service
    remote_src: yes

- name: Replace in Redis Sentinel Service File
  become: yes
  become_user: root
  replace:
    path: /etc/systemd/system/redis-sentinel.service
    regexp: '--supervised systemd --daemonize no'
    replace: '/etc/redis/sentinel.conf - sentinel'

- name: Replace in Redis Sentinel Service File
  become: yes
  become_user: root
  replace:
    path: /etc/systemd/system/redis-sentinel.service
    regexp: 'Type=notify'
    replace: 'Type=forking'

- name: Create Redis Group.
  become: yes
  become_user: root
  group:
    name: redis
    system: yes
    state: present

- name: Add Redis System User.
  become: yes
  become_user: root
  user:
    name: redis
    group: redis
    system: yes
    create_home: no

- name: Create Redis Data Directory.
  become: yes
  become_user: root
  file:
    path: /var/lib/redis
    state: directory
    mode: 0770
    owner: redis
    group: redis

- name: Create Redis Log Directory.
  become: yes
  become_user: root
  file:
    path: /var/log/redis
    state: directory
    mode: 0770
    owner: redis
    group: redis

- name: Register Redis Server Service.
  become: yes
  become_user: root
  service: "name=redis-server state=started enabled=yes"
  notify: Restart Redis Server

- name: Register Redis Sentinel Service.
  become: yes
  become_user: root
  service: "name=redis-sentinel state=started enabled=yes"
  notify: Restart Redis Sentinel

...
