# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Check whether Redis server is installed.
  stat:
    path: "{{ redis_bin }}"
  register: redis_server_installed

- name: Check Redis version.
  command:
    cmd: "{{ redis_bin }} -v"
  register: redis_version_installed
  when: redis_server_installed.stat.exists
  changed_when: false

- name: Determine version.
  set_fact:
    installed_redis_server_version: "{{ redis_version_installed.stdout | regex_search('^Redis server v=(\\d+\\.\\d+\\.\\d+)', '\\1') | first }}"
  when: redis_server_installed.stat.exists

- name: Output version strings.
  debug:
    msg: "Installed version: {{ installed_redis_server_version }}, version to be installed: {{ redis_version }}."
  when: installed_redis_server_version is defined

- name: Check if version strings are equal.
  set_fact:
    is_redis_server_version_equal: "{{ installed_redis_server_version is version(redis_version, operator='==', strict=True) }}"
  when: redis_server_installed.stat.exists

- name: Install dependencies.
  become: yes
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ redis_dependencies }}"

- name: Create Redis Group.
  become: yes
  group:
    name: "{{ redis_group }}"
    system: yes
    state: present

- name: Add Redis System User.
  become: yes
  user:
    name: "{{ redis_user }}"
    group: "{{ redis_group }}"
    system: yes
    create_home: no

- name: Continue if Redis is not installed or versions are not equal.
  when: not redis_server_installed.stat.exists or not is_redis_server_version_equal
  block:
    - name: Download and extract redis-{{ redis_version }}.tar.gz
      become: yes
      unarchive:
        src: "{{ redis_download_url }}"
        dest: "{{ redis_build_dir | dirname }}"
        mode: 0755
        owner: root
        group: root
        remote_src: yes

    - name: Build Redis.
      become: yes
      make:
        chdir: "{{ redis_build_dir }}"

    - name: Install Redis.
      become: yes
      make:
        chdir: "{{ redis_build_dir }}"
        target: install
      notify:
        - Restart Redis Server
        - Restart Redis Sentinel

    - name: Remove current Redis Build Directory.
      file:
        path: "{{ redis_build_dir }}"
        state: absent
      when: redis_version is defined

- name: Create Redis Server Service file.
  become: yes
  template:
    src: "redis-server.service.j2"
    dest: "{{ redis_server_service_file }}"
    mode: 0640
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  notify:
    - Reread Systemd Configs
    - Restart Redis Server

- name: Create Redis Sentinel Service file.
  become: yes
  template:
    src: "redis-sentinel.service.j2"
    dest: "{{ redis_sentinel_service_file }}"
    mode: 0640
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  notify:
    - Reread Systemd Configs
    - Restart Redis Sentinel

- name: Create Redis Configuration Directory.
  become: yes
  file:
    path: "{{ redis_configuration_dir }}"
    state: directory
    mode: 0755
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"

- name: Configure Redis.
  become: yes
  template:
    src: redis.conf.j2
    dest: "{{ redis_server_configuration_file }}"
    mode: 0640
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  notify: Restart Redis Server

- name: Configure Sentinel.
  become: yes
  template:
    src: sentinel.conf.j2
    dest: "{{ redis_sentinel_configuration_file }}"
    mode: 0640
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"
  register: sentinel_configuration
  # Redis adds some extra auto-generated lines to the file which will be
  # overridden and hence this step always results in state "changed".
  changed_when:
    - sentinel_configuration.stderr is defined
  notify: Restart Redis Sentinel

- name: Create Redis Lib Directory.
  become: yes
  file:
    path: "{{ redis_lib_dir }}"
    state: directory
    mode: 0770
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"

- name: Create Redis Log Directory.
  become: yes
  file:
    path: "{{ redis_log_dir }}"
    state: directory
    mode: 0770
    owner: "{{ redis_user }}"
    group: "{{ redis_group }}"

- name: Register Redis Server Service.
  become: yes
  service:
    name: "{{ redis_server_service_name }}"
    state: started
    enabled: yes
  notify: Restart Redis Server

- name: Register Redis Sentinel Service.
  become: yes
  service:
    name: "{{ redis_sentinel_service_name }}"
    state: started
    enabled: yes
  notify: Restart Redis Sentinel

...
