# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance_redis
    image: ${MOLECULE_IMAGE:-ghcr.io/hifis-net/ubuntu-systemd:22.04}
    pre_build_image: true
    privileged: true
    systemd: always
    tty: true
    override_command: false
lint: |
  yamllint --strict --format colored . &&
  ansible-lint -v --force-color --offline --exclude .pipenv/ .
provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: "yaml"
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
verifier:
  name: ansible

...
