# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
- name: Prepare
  hosts: all
  tasks:
    - name: Install dependencies
      apt:
        name:
          - ca-certificates   # for Redis download
          - iproute2          # for gathering network facts
          - net-tools         # for gathering listening ports
          - python3-redis     # required by community.general.redis
          - sudo              # for `become` privilege escalation
        update_cache: yes
        state: present
