# SPDX-FileCopyrightText: 2020 Helmholtz Centre for Environmental Research (UFZ)
# SPDX-FileCopyrightText: 2020 Helmholtz-Zentrum Dresden-Rossendorf (HZDR)
#
# SPDX-License-Identifier: Apache-2.0

---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  vars:
    redis_server_service_name: 'redis-server'
    redis_sentinel_service_name: 'redis-sentinel'
    redis_server_port: 6379
    redis_sentinel_port: 26379
    redis_ports:
      - "{{ redis_server_port }}"
      - "{{ redis_sentinel_port }}"
  tasks:
    - name: Populate service facts
      service_facts:
      register: services_state

    - name: Check that Redis is running on instance
      assert:
        that:
          - services_state.ansible_facts.services[redis_server_service_name + '.service'].state is search("running")
          - services_state.ansible_facts.services[redis_sentinel_service_name + '.service'].state is search("running")

    - name: Gather facts on listening ports.
      listen_ports_facts:

    - name: Check if Redis is listening on TCP ports
      vars:
        tcp_listen: "{{ ansible_facts.tcp_listen | selectattr('port', 'in', redis_ports) | list }}"
      assert:
        that:
          - item.name == redis_server_service_name
      loop: "{{ tcp_listen }}"
